name: xtraevent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y automake git build-essential gettext
    - name: Compile xtraevent Python and process .po files
      run: |
        python3 -m compileall .
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        echo "Done!"
